services:
  - type: web
    name: runmate
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://runmate-sqpa.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: KAKAO_CLIENT_ID
        sync: false
      - key: KAKAO_CLIENT_SECRET
        sync: false
      - key: NAVER_CLIENT_ID
        sync: false
      - key: NAVER_CLIENT_SECRET
        sync: false
